[package]
name = "canvasapi"
version = "0.1.0"
authors = ["Thibaut Vandervelden <thvdveld@vub.be>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = { version = "2", features = ["openssl"] }
actix-rt = "1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
dotenv = "0.15"
anyhow = "1.0"
